trigger: none
stages: 
- stage: build
  displayName: test
  jobs: 
  - job: nuild
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - script: |
        echo "stage 1 building"
- stage: Test
  dependsOn: build
  jobs: 
  - job: test
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - script: echo "stage 2 testing"
- stage:  Deploying
  displayName: Deploying
  jobs: 
  - job: Deploying
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - script: echo "deploying..."
      